# Generated by Django 4.2.29 on 2026-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanstatus',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scanstatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
