# Generated by Django 4.2.29 on 2026-03-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_scanstatus_photo_url_alter_scanstatus_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_qr', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_type', models.CharField(max_length=50)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=100)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen.student')),
            ],
        ),
    ]
